os: linux

dist: xenial

sudo: false

language: node_js

node_js:
  - 'lts/*'

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      addons:
        chrome: stable
      node_js:
        - 'lts/*'
      env:
        - BROWSERS=ChromeHeadlessNoSandbox
      script:
        - npm run travis
    - os: linux
      dist: xenial
      sudo: false
      addons:
        firefox: latest
      node_js:
        - 'lts/*'
      env:
        - BROWSERS=FirefoxHeadless
      script:
        - npm run travis
    - os: osx
      osx_image: xcode10.1
      node_js:
        - 'lts/*'
      env:
        - BROWSERS=Safari
      script:
        - npm run travis
    - os: osx
      osx_image: xcode9.2
      node_js:
        - 'lts/*'
      env:
        - BROWSERS=Safari
      script:
        - npm run travis

git:
  depth: 3

cache: npm

script:
  - npm run lint
  - npm run build
